export const FETCH_PENDING = "FETCH_USERS_PENDING";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_STATISTIC_SUCCESS = "FETCH_USERS_STATISTIC_SUCCESS";
export const FETCH_ERROR = "FETCH_USERS_ERROR";
export const FETCH_USER_BY_ID = 'FETCH_USER_BY_ID';
export const FETCH_STATISTIC_ONE_USER = 'FETCH_STATISTIC_ONE_USER';